version: '3'

services:
  openvpn-client:
    image: frauhottelmann/openvpn-client:2.6.12
    container_name: openvpn-client
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    command: --config /vpn/client.ovpn --askpass /vpn/client.pwd --auth-nocache
    volumes:
      - ./client/:/vpn
    network_mode: "bridge"
    
